#!/usr/bin/env bash

## Watch for file changes in the theme to trigger a build.  Will not work with browsersync.
## This should be run after "fin feinstall".
##
## Usage: fin fewatch

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
CURRENT_PATH=$(pwd)

WATCH_URL="http://${VIRTUAL_HOST}"

echo "Opening: ${WATCH_URL}"

open "${WATCH_URL}"

fin exec npm run watch
